"""empty message

Revision ID: 5742ac0d7e98
Revises: d9e411b650e1
Create Date: 2020-12-07 18:49:04.131311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5742ac0d7e98'
down_revision = 'd9e411b650e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'img')
    # ### end Alembic commands ###
